cat: my-cat.c
	gcc -o my-cat.out my-cat.c -Wall -Werror

grep: my-grep.c
	gcc -o my-grep.out my-grep.c -Wall -Werror

zip: my-zip.c
	gcc -o my-zip.out my-zip.c -Wall -Werror

unzip: my-unzip.c
	gcc -o my-unzip.out my-unzip.c -Wall -Werror

all: cat grep zip unzip
